name: tulaby_clean_code
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^8.1.4
  dartz: ^0.10.1
  device_preview: ^1.2.0
  dio: ^5.7.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  # flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^8.1.6
  flutter_otp_text_field: ^1.4.0+2
  flutter_svg: ^2.0.16
  get_it: ^8.0.3
  go_router: ^14.6.2
  intl: ^0.19.0
  jwt_decoder: ^2.0.1
  mobile_scanner: ^6.0.2
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600

    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Regular.ttf

flutter_assets:
  assets_path: assets/images
  output_path: lib/utls
  filename: app_assets.dart
  field_prefix: null
