name: tulaby_clean_code
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  go_router: ^14.6.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600

    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Regular.ttf

flutter_assets:
  assets_path: assets/images
  output_path: lib/utls
  filename: app_assets.dart
  field_prefix: null
